kumuluzee:
  opentracing:
    service-name: Customers Microservice
    selected-tracer: jaeger
    available-tracers:
      jaeger:
        reporter_host: localhost
        reporter_port: 5775
    server:
      operation-name-provider: http-path
      skip-pattern: /openapi.*|/health.*