kumuluzee:
  name: Customers Microservice
  server:
    http:
      port: 3000
  opentracing:
    reporter_host: localhost
    reporter_port: 5775
    server:
      operation-name-provider: http-path
      skip-pattern: /openapi.*|/health.*