kumuluzee:
  name: Orders Microservice
  server:
    http:
      port: 3001
  opentracing:
    reporter_host: localhost
    reporter_port: 5775
    server:
      operation-name-provider: class-method
      skip-pattern: /openapi.*|/health.*