kumuluzee:
  name: Orders Microservice
  server:
    http:
      port: 3001
  opentracing:
    jaeger:
      agent-host: localhost
      agent-port: 5775
    zipkin:
      agent-host: http://localhost
      agent-port: 9411

mp:
  opentracing:
    server:
      operation-name-provider: class-method
      skip-pattern: /openapi.*|/health.*